/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LecturerRouteImport } from './routes/lecturer'
import { Route as CourseRepRouteImport } from './routes/course-rep'
import { Route as AeirgRouteImport } from './routes/aeirg'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AeirgIndexRouteImport } from './routes/aeirg.index'
import { Route as LecturerCoursesRouteImport } from './routes/lecturer.courses'
import { Route as CourseRepTimetableRouteImport } from './routes/course-rep.timetable'
import { Route as CourseRepStudentsRouteImport } from './routes/course-rep.students'
import { Route as CourseRepCoursesRouteImport } from './routes/course-rep.courses'
import { Route as AeirgStudentRouteImport } from './routes/aeirg.student'
import { Route as AeirgLoginRouteImport } from './routes/aeirg.login'
import { Route as AeirgAdminRouteImport } from './routes/aeirg.admin'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRoute = LecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRepRoute = CourseRepRouteImport.update({
  id: '/course-rep',
  path: '/course-rep',
  getParentRoute: () => rootRouteImport,
} as any)
const AeirgRoute = AeirgRouteImport.update({
  id: '/aeirg',
  path: '/aeirg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AeirgIndexRoute = AeirgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AeirgRoute,
} as any)
const LecturerCoursesRoute = LecturerCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LecturerRoute,
} as any)
const CourseRepTimetableRoute = CourseRepTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => CourseRepRoute,
} as any)
const CourseRepStudentsRoute = CourseRepStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CourseRepRoute,
} as any)
const CourseRepCoursesRoute = CourseRepCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => CourseRepRoute,
} as any)
const AeirgStudentRoute = AeirgStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AeirgRoute,
} as any)
const AeirgLoginRoute = AeirgLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AeirgRoute,
} as any)
const AeirgAdminRoute = AeirgAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AeirgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aeirg': typeof AeirgRouteWithChildren
  '/course-rep': typeof CourseRepRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRoute
  '/aeirg/admin': typeof AeirgAdminRoute
  '/aeirg/login': typeof AeirgLoginRoute
  '/aeirg/student': typeof AeirgStudentRoute
  '/course-rep/courses': typeof CourseRepCoursesRoute
  '/course-rep/students': typeof CourseRepStudentsRoute
  '/course-rep/timetable': typeof CourseRepTimetableRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/aeirg/': typeof AeirgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course-rep': typeof CourseRepRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRoute
  '/aeirg/admin': typeof AeirgAdminRoute
  '/aeirg/login': typeof AeirgLoginRoute
  '/aeirg/student': typeof AeirgStudentRoute
  '/course-rep/courses': typeof CourseRepCoursesRoute
  '/course-rep/students': typeof CourseRepStudentsRoute
  '/course-rep/timetable': typeof CourseRepTimetableRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/aeirg': typeof AeirgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aeirg': typeof AeirgRouteWithChildren
  '/course-rep': typeof CourseRepRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRoute
  '/aeirg/admin': typeof AeirgAdminRoute
  '/aeirg/login': typeof AeirgLoginRoute
  '/aeirg/student': typeof AeirgStudentRoute
  '/course-rep/courses': typeof CourseRepCoursesRoute
  '/course-rep/students': typeof CourseRepStudentsRoute
  '/course-rep/timetable': typeof CourseRepTimetableRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/aeirg/': typeof AeirgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aeirg'
    | '/course-rep'
    | '/lecturer'
    | '/login'
    | '/profile'
    | '/student'
    | '/aeirg/admin'
    | '/aeirg/login'
    | '/aeirg/student'
    | '/course-rep/courses'
    | '/course-rep/students'
    | '/course-rep/timetable'
    | '/lecturer/courses'
    | '/aeirg/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/course-rep'
    | '/lecturer'
    | '/login'
    | '/profile'
    | '/student'
    | '/aeirg/admin'
    | '/aeirg/login'
    | '/aeirg/student'
    | '/course-rep/courses'
    | '/course-rep/students'
    | '/course-rep/timetable'
    | '/lecturer/courses'
    | '/aeirg'
  id:
    | '__root__'
    | '/'
    | '/aeirg'
    | '/course-rep'
    | '/lecturer'
    | '/login'
    | '/profile'
    | '/student'
    | '/aeirg/admin'
    | '/aeirg/login'
    | '/aeirg/student'
    | '/course-rep/courses'
    | '/course-rep/students'
    | '/course-rep/timetable'
    | '/lecturer/courses'
    | '/aeirg/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AeirgRoute: typeof AeirgRouteWithChildren
  CourseRepRoute: typeof CourseRepRouteWithChildren
  LecturerRoute: typeof LecturerRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  StudentRoute: typeof StudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-rep': {
      id: '/course-rep'
      path: '/course-rep'
      fullPath: '/course-rep'
      preLoaderRoute: typeof CourseRepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeirg': {
      id: '/aeirg'
      path: '/aeirg'
      fullPath: '/aeirg'
      preLoaderRoute: typeof AeirgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeirg/': {
      id: '/aeirg/'
      path: '/'
      fullPath: '/aeirg/'
      preLoaderRoute: typeof AeirgIndexRouteImport
      parentRoute: typeof AeirgRoute
    }
    '/lecturer/courses': {
      id: '/lecturer/courses'
      path: '/courses'
      fullPath: '/lecturer/courses'
      preLoaderRoute: typeof LecturerCoursesRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/course-rep/timetable': {
      id: '/course-rep/timetable'
      path: '/timetable'
      fullPath: '/course-rep/timetable'
      preLoaderRoute: typeof CourseRepTimetableRouteImport
      parentRoute: typeof CourseRepRoute
    }
    '/course-rep/students': {
      id: '/course-rep/students'
      path: '/students'
      fullPath: '/course-rep/students'
      preLoaderRoute: typeof CourseRepStudentsRouteImport
      parentRoute: typeof CourseRepRoute
    }
    '/course-rep/courses': {
      id: '/course-rep/courses'
      path: '/courses'
      fullPath: '/course-rep/courses'
      preLoaderRoute: typeof CourseRepCoursesRouteImport
      parentRoute: typeof CourseRepRoute
    }
    '/aeirg/student': {
      id: '/aeirg/student'
      path: '/student'
      fullPath: '/aeirg/student'
      preLoaderRoute: typeof AeirgStudentRouteImport
      parentRoute: typeof AeirgRoute
    }
    '/aeirg/login': {
      id: '/aeirg/login'
      path: '/login'
      fullPath: '/aeirg/login'
      preLoaderRoute: typeof AeirgLoginRouteImport
      parentRoute: typeof AeirgRoute
    }
    '/aeirg/admin': {
      id: '/aeirg/admin'
      path: '/admin'
      fullPath: '/aeirg/admin'
      preLoaderRoute: typeof AeirgAdminRouteImport
      parentRoute: typeof AeirgRoute
    }
  }
}

interface AeirgRouteChildren {
  AeirgAdminRoute: typeof AeirgAdminRoute
  AeirgLoginRoute: typeof AeirgLoginRoute
  AeirgStudentRoute: typeof AeirgStudentRoute
  AeirgIndexRoute: typeof AeirgIndexRoute
}

const AeirgRouteChildren: AeirgRouteChildren = {
  AeirgAdminRoute: AeirgAdminRoute,
  AeirgLoginRoute: AeirgLoginRoute,
  AeirgStudentRoute: AeirgStudentRoute,
  AeirgIndexRoute: AeirgIndexRoute,
}

const AeirgRouteWithChildren = AeirgRoute._addFileChildren(AeirgRouteChildren)

interface CourseRepRouteChildren {
  CourseRepCoursesRoute: typeof CourseRepCoursesRoute
  CourseRepStudentsRoute: typeof CourseRepStudentsRoute
  CourseRepTimetableRoute: typeof CourseRepTimetableRoute
}

const CourseRepRouteChildren: CourseRepRouteChildren = {
  CourseRepCoursesRoute: CourseRepCoursesRoute,
  CourseRepStudentsRoute: CourseRepStudentsRoute,
  CourseRepTimetableRoute: CourseRepTimetableRoute,
}

const CourseRepRouteWithChildren = CourseRepRoute._addFileChildren(
  CourseRepRouteChildren,
)

interface LecturerRouteChildren {
  LecturerCoursesRoute: typeof LecturerCoursesRoute
}

const LecturerRouteChildren: LecturerRouteChildren = {
  LecturerCoursesRoute: LecturerCoursesRoute,
}

const LecturerRouteWithChildren = LecturerRoute._addFileChildren(
  LecturerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AeirgRoute: AeirgRouteWithChildren,
  CourseRepRoute: CourseRepRouteWithChildren,
  LecturerRoute: LecturerRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  StudentRoute: StudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
