/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LecturerRouteImport } from './routes/lecturer'
import { Route as CourseRepRouteImport } from './routes/course-rep'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as LecturerCoursesRouteImport } from './routes/lecturer.courses'
import { Route as CourseRepTimetableRouteImport } from './routes/course-rep.timetable'
import { Route as CourseRepStudentsRouteImport } from './routes/course-rep.students'
import { Route as CourseRepCoursesRouteImport } from './routes/course-rep.courses'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRoute = LecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRepRoute = CourseRepRouteImport.update({
  id: '/course-rep',
  path: '/course-rep',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const LecturerCoursesRoute = LecturerCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LecturerRoute,
} as any)
const CourseRepTimetableRoute = CourseRepTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => CourseRepRoute,
} as any)
const CourseRepStudentsRoute = CourseRepStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CourseRepRoute,
} as any)
const CourseRepCoursesRoute = CourseRepCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => CourseRepRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course-rep': typeof CourseRepRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRouteWithChildren
  '/course-rep/courses': typeof CourseRepCoursesRoute
  '/course-rep/students': typeof CourseRepStudentsRoute
  '/course-rep/timetable': typeof CourseRepTimetableRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/student/courses': typeof StudentCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course-rep': typeof CourseRepRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRouteWithChildren
  '/course-rep/courses': typeof CourseRepCoursesRoute
  '/course-rep/students': typeof CourseRepStudentsRoute
  '/course-rep/timetable': typeof CourseRepTimetableRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/student/courses': typeof StudentCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course-rep': typeof CourseRepRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/student': typeof StudentRouteWithChildren
  '/course-rep/courses': typeof CourseRepCoursesRoute
  '/course-rep/students': typeof CourseRepStudentsRoute
  '/course-rep/timetable': typeof CourseRepTimetableRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/student/courses': typeof StudentCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/course-rep'
    | '/lecturer'
    | '/login'
    | '/profile'
    | '/student'
    | '/course-rep/courses'
    | '/course-rep/students'
    | '/course-rep/timetable'
    | '/lecturer/courses'
    | '/student/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/course-rep'
    | '/lecturer'
    | '/login'
    | '/profile'
    | '/student'
    | '/course-rep/courses'
    | '/course-rep/students'
    | '/course-rep/timetable'
    | '/lecturer/courses'
    | '/student/courses'
  id:
    | '__root__'
    | '/'
    | '/course-rep'
    | '/lecturer'
    | '/login'
    | '/profile'
    | '/student'
    | '/course-rep/courses'
    | '/course-rep/students'
    | '/course-rep/timetable'
    | '/lecturer/courses'
    | '/student/courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseRepRoute: typeof CourseRepRouteWithChildren
  LecturerRoute: typeof LecturerRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-rep': {
      id: '/course-rep'
      path: '/course-rep'
      fullPath: '/course-rep'
      preLoaderRoute: typeof CourseRepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/lecturer/courses': {
      id: '/lecturer/courses'
      path: '/courses'
      fullPath: '/lecturer/courses'
      preLoaderRoute: typeof LecturerCoursesRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/course-rep/timetable': {
      id: '/course-rep/timetable'
      path: '/timetable'
      fullPath: '/course-rep/timetable'
      preLoaderRoute: typeof CourseRepTimetableRouteImport
      parentRoute: typeof CourseRepRoute
    }
    '/course-rep/students': {
      id: '/course-rep/students'
      path: '/students'
      fullPath: '/course-rep/students'
      preLoaderRoute: typeof CourseRepStudentsRouteImport
      parentRoute: typeof CourseRepRoute
    }
    '/course-rep/courses': {
      id: '/course-rep/courses'
      path: '/courses'
      fullPath: '/course-rep/courses'
      preLoaderRoute: typeof CourseRepCoursesRouteImport
      parentRoute: typeof CourseRepRoute
    }
  }
}

interface CourseRepRouteChildren {
  CourseRepCoursesRoute: typeof CourseRepCoursesRoute
  CourseRepStudentsRoute: typeof CourseRepStudentsRoute
  CourseRepTimetableRoute: typeof CourseRepTimetableRoute
}

const CourseRepRouteChildren: CourseRepRouteChildren = {
  CourseRepCoursesRoute: CourseRepCoursesRoute,
  CourseRepStudentsRoute: CourseRepStudentsRoute,
  CourseRepTimetableRoute: CourseRepTimetableRoute,
}

const CourseRepRouteWithChildren = CourseRepRoute._addFileChildren(
  CourseRepRouteChildren,
)

interface LecturerRouteChildren {
  LecturerCoursesRoute: typeof LecturerCoursesRoute
}

const LecturerRouteChildren: LecturerRouteChildren = {
  LecturerCoursesRoute: LecturerCoursesRoute,
}

const LecturerRouteWithChildren = LecturerRoute._addFileChildren(
  LecturerRouteChildren,
)

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseRepRoute: CourseRepRouteWithChildren,
  LecturerRoute: LecturerRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
